### ISSUE TITLE
lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/add2md/R/add2md.rdb' is corrupt

### ISSUE THREAD

**Issue by JiaxiangBU** [JiaxiangBU/add2md#2]
```
> library(add2md)
> m1()
错误: lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/add2md/R/add2md.rdb' is corrupt
此外: Warning messages:
1: 重新评估被中断的许诺 
2: internal error -3 in R_decompress1 
```

**Comment by JiaxiangBU** [comment]
On windows it works well.

```
> library(add2md)
> m1()
[](123)
-- The text is already pasted on your system copyboard! ------------------------
```

**Comment by gaowenxin95** [comment]
我也遇到这个问题了
restarting interrupted promise evaluationinternal error -3 in R_decompress1Error: lazy-load database 'E:/R-3.6.0/library/PooledMeanGroup/R/PooledMeanGroup.rdb' is corrupt，就是安装你给我的安装包，我安装之后出现的
@JiaxiangBU

**Comment by JiaxiangBU** [comment]
> 我也遇到这个问题了
> restarting interrupted promise evaluationinternal error -3 in R_decompress1Error: lazy-load database 'E:/R-3.6.0/library/PooledMeanGroup/R/PooledMeanGroup.rdb' is corrupt，就是安装你给我的安装包，我安装之后出现的
> @JiaxiangBU

@gaowenxin95 反馈到对应项目 https://github.com/JiaxiangBU/PooledMeanGroup
